# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d01240624d4fe6a79bc7c41fd0978b4c25c3157608e7624672881be5af028b2b2ec58714f4d74a8a8502d50c8f8205ba5d43f3ffc53b151c5eec349d21928ed

test:
  secret_key_base: 3feac09fbbc9e97e35f0b012429579b2b3f71936ed128608f71953ae53705e757fb7228ad864c9813461a197adeb2b14e6d9ba9e00fc079788dd2c50021b2173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
